name: CI/CD using github actions & docker

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application.properties
        run: |
          echo "${{ secrets.APPLICATION }}" > src/main/resources/application.properties

      - name: Create application-prod.properties
        run: |
          echo "${{ secrets.APPLICATION_PROD }}" > src/main/resources/application-prod.properties

      - name: Create application-test.properties
        run: |
          echo "${{ secrets.APPLICATION_TEST }}" > src/test/resources/application-test.properties

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/spring-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-app:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/spring-app:${{ github.sha }}
            docker stop spring-app || true
            docker rm spring-app || true
            docker run -d -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              --name spring-app \
              ${{ secrets.DOCKER_USERNAME }}/spring-app:${{ github.sha }}
